# Generated by Django 4.2.13 on 2024-06-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_order', 'Can create orders')]},
        ),
    ]
